### PR TITLE
chore: Update README.md

### LINKED ISSUE #38: Update README to include retrofit
**Describe the chore**
As now it uses Retrofit the dependencies README can be updated
and the workflow can also be updated

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by athiranair2000**
Fixed part of #38 
Changes: Updated README.md file with retrofit mentioned as a dependency.

### CODE REVIEW

**Review by yashk2000 — APPROVED** [review]
@athiranair2000 great work. Thanks :grin: 

I think we would also need to update the workflow of the app. Would you like to work on that too?

**Comment by athiranair2000** [comment]
Ya sure,will update workflow of app as well :+1:

**Comment by yashk2000** [comment]
Great :+1:

**Comment by immadisairaj** [comment]
@athiranair2000 can you update the PR title to be appropriate. `fix` represents this is a fix for a bug which is not. And the title has to be something like `update` instead of `updated`.

**Review by immadisairaj — APPROVED** [review]

**Comment by immadisairaj** [comment]
> I think we would also need to update the workflow of the app. Would you like to work on that too?

@yashk2000 the workflow can be updated later with the other issue #119

**Comment by yashk2000** [comment]
@immadisairaj yes. We can have a separate pr for that. This can be merged :+1:

**Review by ajay-prabhakar — COMMENTED** [review]
As we are thinking to use the firebase then there is no need of retrofit
So, I think this PR is no need

**Comment by yashk2000** [comment]
> As we are thinking to use the firebase then there is no need of retrofit
> So, I think this PR is no need

When we shift to firebase then we'll remove this. Until we shift to firebase, this has to be in readme.

**Comment by ajay-prabhakar** [comment]
> > As we are thinking to use the firebase then there is no need of retrofit
> > So, I think this PR is no need
> 
> When we shift to firebase then we'll remove this. Until we shift to firebase, this has to be in readme.

Fine then :rocket:

**Review by ajay-prabhakar — APPROVED** [review]

**Pull request merged**
