### PR TITLE
chore: Migrated to Androidx

### LINKED ISSUE #123: Migrate the entire codebase into Androidx
**Describe the chore**
Migrate the entire codebase into androidX as it uses to develop, test, package, version and release libraries within Jetpack.

**Would you like to work on the issue?** (Yes/No)
No

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixed #123 
Migrated the entire code base to AndroidX

### CODE REVIEW

**Review by ajay-prabhakar — CHANGES_REQUESTED** [review]
@ShivangiSingh17 great work but you have so many unused imports so, remove all unused imports to fix the build issue you can do that easily by `ctrl+alt+O` in android studio

**Review by yashk2000 — CHANGES_REQUESTED** [review]
Please handle the imports properly.

**Comment by yashk2000** [comment]
@ShivangiSingh17 please fix the above mentioned issue ASAP.

**Comment by ShivangiSingh17** [comment]
Yes, will do.

**Review by yashk2000 — APPROVED** [review]
Great work @ShivangiSingh17. Thanks :smile:

**Review by immadisairaj — APPROVED** [review]

**Review by ajay-prabhakar — APPROVED** [review]
:tada:

**Pull request merged**
